version: "3"

networks:
  app_net:
    driver: ${NETWORKS_DRIVER}
    driver_opts:
      com.docker.network.enable_ipv6: ${ENABLE_IPV6}
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}

services:
  tool-mysql8:
    image: mysql:8
    restart: always
    privileged: "true"
    container_name: tool-mysql8
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql8/conf/my.cnf:/etc/my.cnf
      - ./mysql8/data:/var/lib/mysql
    networks:
      app_net:
        ipv4_address: ${MYSQL_SUBNET_IP}
    expose:
      - ${MYSQL_PORT}
    ports:
      - ${MYSQL_PORT}:3306

  tool-redis5:
    image: redis:5
    restart: always
    privileged: "true"
    container_name: tool-redis5
    volumes:
      - ./redis5/conf/redis.conf:/etc/redis/redis.conf
      - ./redis5/data:/var/lib/redis
    networks:
      app_net:
        ipv4_address: ${REDIS_SUBNET_IP}
    expose:
      - ${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:6379

  tool-nginx:
    image: nginx:latest
    restart: always
    privileged: "true"
    container_name: tool-nginx
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/data:/usr/share/nginx/html
      - ./nginx/sites-enabled:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ${APP_PROJECT_PATH}:/work
    networks:
      app_net:
        ipv4_address: ${NGINX_IP}
    expose:
      - ${NGINX_PORT}
    ports:
      - ${NGINX_PORT}:80

  tool-phpfpm73:
    image: php:7.3-fpm
    restart: always
    privileged: "true"
    container_name: tool-phpfpm73
    volumes:
      - ./phpfpm73/conf/php.ini:/usr/local/etc/php/php.ini
      - ./phpfpm73/conf/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./phpfpm73/log:/usr/local/var/log
      - ${APP_PROJECT_PATH}:/work
    networks:
      app_net:
        ipv4_address: ${PHPFPM_IP}
    expose:
      - ${PHPFPM_PORT}
    ports:
      - ${PHPFPM_PORT}:9000

  tool-elasticsearch7:
    image: elasticsearch:7.3.0
    restart: always
    privileged: "true"
    container_name: tool-elasticsearch7
    environment:
      - discovery.type=single-node
    volumes:
      - ./elasticsearch7/conf:/usr/share/elasticsearch/conf
      - ./elasticsearch7/data:/usr/share/elasticsearch/data
      - ./elasticsearch7/logs:/usr/share/elasticsearch/logs
    networks:
      app_net:
        ipv4_address: ${ELASTICSEARCH_IP}
    expose:
      - ${ELASTICSEARCH_HTTP_PORT}
      - ${ELASTICSEARCH_TCP_PORT}
    ports:
      - ${ELASTICSEARCH_HTTP_PORT}:9200
      - ${ELASTICSEARCH_TCP_PORT}:9300