version: "3.7"

networks:
  app_net:
    driver: ${NETWORKS_DRIVER}
    driver_opts:
      com.docker.network.enable_ipv6: ${ENABLE_IPV6}
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}

services:
  tool-mysql8:
    image: mysql:8
    restart: always
    privileged: "true"
    container_name: tool-mysql8
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql8/conf/my.cnf:/etc/my.cnf
      - ./mysql8/data:/var/lib/mysql
    networks:
      app_net:
        ipv4_address: ${MYSQL_SUBNET_IP}
    expose:
      - 3306
    ports:
      - ${MYSQL_PORT}:3306

  tool-postgres13:
    image: postgres:13
    privileged: "true"
    container_name: tool-postgres13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRE_PASSWORD}
    volumes:
      - ./postgresql13/postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      app_net:
        ipv4_address: ${POSTGRE_IP}
    expose:
      - 5432
    ports:
      - ${POSTGRE_PORT}:5432

  tool-redis6:
    image: redis:6
    privileged: "true"
    container_name: tool-redis6
    volumes:
      - ./redis6/conf/redis.conf:/etc/redis/redis.conf
      - ./redis6/data:/var/lib/redis
    networks:
      app_net:
        ipv4_address: ${REDIS_SUBNET_IP}
    expose:
      - 6379
    ports:
      - ${REDIS_PORT}:6379

  tool-elasticsearch7:
    image: elasticsearch:7.9.0
    privileged: "true"
    container_name: tool-elasticsearch7
    environment:
      - discovery.type=single-node
    volumes:
      - ./elasticsearch7/conf:/usr/share/elasticsearch/conf
      - ./elasticsearch7/data:/usr/share/elasticsearch/data
      - ./elasticsearch7/logs:/usr/share/elasticsearch/logs
    networks:
      app_net:
        ipv4_address: ${ELASTICSEARCH_IP}
    expose:
      - 9200
      - 9300
    ports:
      - ${ELASTICSEARCH_HTTP_PORT}:9200
      - ${ELASTICSEARCH_TCP_PORT}:9300

  tool-adminer4:
    image: adminer:4
    privileged: "true"
    container_name: tool-adminer4
    volumes:
      - ./adminer4/adminer.css:/var/www/html/adminer.css
    networks:
      app_net:
        ipv4_address: ${ADMINER_IP}
    expose:
      - 8080
    ports:
      - ${ADMINER_PORT}:8080

  tool-mosquitto16:
    image: eclipse-mosquitto:1.6
    privileged: "true"
    container_name: tool-mosquitto16
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      app_net:
        ipv4_address: ${MQTT_IP}
    expose:
      - 1883
      - 9001
    ports:
      - ${MQTT_PORT}:1883
      - ${MQTT_PORT_EX}:9001

  tool-rabbitmq3:
    image: rabbitmq:3-management
    privileged: "true"
    container_name: tool-rabbitmq3
    environment:
      - RABBITMQ_DEFAULT_VHOST=rabbit0
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - ./rabbitmq3/data:/var/lib/rabbitmq
    networks:
      app_net:
        ipv4_address: ${RABBITMQ_IP}
    expose:
      - 5672
      - 15672
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_MANAGE_PORT}:15672

  tool-nginx:
    image: nginx:latest
    privileged: "true"
    container_name: tool-nginx
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/data:/usr/share/nginx/html
      - ./nginx/sites-enabled:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ${APP_PROJECT_PATH}:/work
    networks:
      app_net:
        ipv4_address: ${NGINX_IP}
    expose:
      - 80
    ports:
      - ${NGINX_PORT}:80
