version: "3"

networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 177.18.0.0/16

services:
  mysql8:
    image: mysql:8
    restart: always
    privileged: "true"
    container_name: tool-mysql8
    environment:
      - MYSQL_USER="worker"
      - MYSQL_PASSWORD="123456"
      - MYSQL_ROOT_PASSWORD="123456"
    volumes:
      - ./mysql8/conf/my.cnf:/etc/my.cnf
      - ./mysql8/data:/var/lib/mysql
    networks:
      app_net:
        ipv4_address: 177.18.0.2
    expose:
      - 3306
    ports:
      - 3306:3306

  redis5:
    image: redis:5
    restart: always
    privileged: "true"
    container_name: tool-redis5
    volumes:
      - ./redis5/conf/redis.conf:/etc/redis/redis.conf
      - ./redis5/data:/var/lib/redis
    networks:
      app_net:
        ipv4_address: 177.18.0.3
    expose:
      - 6380
    ports:
      - 6380:6379

  elasticsearch7:
    image: elasticsearch:7.3.0
    restart: always
    privileged: "true"
    container_name: tool-elasticsearch7
    volumes:
      - ./elasticsearch7/conf:/usr/share/elasticsearch/conf
      - ./elasticsearch7/data:/usr/share/elasticsearch/data
      - ./elasticsearch7/logs:/usr/share/elasticsearch/logs
    networks:
      app_net:
        ipv4_address: 177.18.0.4
    environment:
      - discovery.type=single-node
    expose:
      - 9200
      - 9300
    ports:
      - 9200:9200
      - 9300:9300

  nginx:
    image: nginx:latest
    restart: always
    privileged: "true"
    container_name: tool-nginx
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/data:/usr/share/nginx/html
      - ./nginx/sites-enabled:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ~/work:/work
    networks:
      app_net:
        ipv4_address:  177.18.0.5
    expose:
      - 80
    ports:
      - 80:80

  php-fpm73:
    image: php:7.3-fpm
    restart: always
    privileged: "true"
    container_name: tool-phpfpm73
    volumes:
      - ./phpfpm73/php.ini-development:/usr/local/etc/php/php.ini-development
      - ./phpfpm73/php.ini-production:/usr/local/etc/php/php.ini-production
      - ./phpfpm73/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ~/work:/work
    networks:
      app_net:
        ipv4_address:  177.18.0.6
    expose:
      - 9001
    ports:
      - 9001:9000