version: "3.7"

networks:
  app_net:
    driver: ${NETWORKS_DRIVER}
    driver_opts:
      com.docker.network.enable_ipv6: ${ENABLE_IPV6}
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}

services:
  tool-mysql8:
    image: mysql:8
    restart: always
    privileged: "true"
    container_name: tool-mysql8
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql8/conf/my.cnf:/etc/my.cnf
      - ./mysql8/data:/var/lib/mysql
    networks:
      app_net:
        ipv4_address: ${MYSQL_SUBNET_IP}
    expose:
      - 3306
    ports:
      - ${MYSQL_PORT}:3306

  tool-redis5:
    image: redis:5
    restart: always
    privileged: "true"
    container_name: tool-redis5
    volumes:
      - ./redis5/conf/redis.conf:/etc/redis/redis.conf
      - ./redis5/data:/var/lib/redis
    networks:
      app_net:
        ipv4_address: ${REDIS_SUBNET_IP}
    expose:
      - 6379
    ports:
      - ${REDIS_PORT}:6379

  tool-nginx:
    image: nginx:latest
    restart: always
    privileged: "true"
    container_name: tool-nginx
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/data:/usr/share/nginx/html
      - ./nginx/sites-enabled:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ${APP_PROJECT_PATH}:/work
    networks:
      app_net:
        ipv4_address: ${NGINX_IP}
    expose:
      - 80
    ports:
      - ${NGINX_PORT}:80

  tool-phpfpm73:
    image: php:7.3-fpm
    restart: always
    privileged: "true"
    container_name: tool-phpfpm73
    volumes:
      - ./phpfpm73/conf/php.ini:/usr/local/etc/php/php.ini
      - ./phpfpm73/conf/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./phpfpm73/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./phpfpm73/log:/usr/local/var/log
      - ${APP_PROJECT_PATH}:/work
    networks:
      app_net:
        ipv4_address: ${PHPFPM_IP}
    expose:
      - 9000
    ports:
      - ${PHPFPM_PORT}:9000

  tool-elasticsearch7:
    image: elasticsearch:7.3.0
    restart: always
    privileged: "true"
    container_name: tool-elasticsearch7
    environment:
      - discovery.type=single-node
    volumes:
      - ./elasticsearch7/conf:/usr/share/elasticsearch/conf
      - ./elasticsearch7/data:/usr/share/elasticsearch/data
      - ./elasticsearch7/logs:/usr/share/elasticsearch/logs
    networks:
      app_net:
        ipv4_address: ${ELASTICSEARCH_IP}
    expose:
      - 9200
      - 9300
    ports:
      - ${ELASTICSEARCH_HTTP_PORT}:9200
      - ${ELASTICSEARCH_TCP_PORT}:9300

  tool-adminer4:
    image: adminer:4
    restart: always
    privileged: "true"
    container_name: tool-adminer4
    volumes:
      - ./adminer4/adminer.css:/var/www/html/adminer.css
    networks:
      app_net:
        ipv4_address: ${ADMINER_IP}
    expose:
      - 8080
    ports:
      - ${ADMINER_PORT}:8080

  tool-ubuntu1804:
    image: ubuntu-php:1.0
    restart: always
    privileged: "true"
    container_name: tool-ubuntu1804
    volumes:
      - ${APP_PROJECT_PATH}:/work
    networks:
      app_net:
        ipv4_address: ${UBUNTU_IP}
    expose:
      - 80
    ports:
      - ${UBUNTU_PORT}:80

  tool-mosquitto16:
    image: eclipse-mosquitto:1.6
    restart: always
    privileged: "true"
    container_name: tool-mosquitto16
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      app_net:
        ipv4_address: ${MQTT_IP}
    expose:
      - 1883
      - 9001
    ports:
      - ${MQTT_PORT}:1883
      - ${MQTT_PORT_EX}:9001

  tool-postgres12:
    image: postgres:12
    restart: always
    privileged: "true"
    container_name: tool-postgres12
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRE_PASSWORD}
    volumes:
      - ./postgresql12/postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      app_net:
        ipv4_address: ${POSTGRE_IP}
    expose:
      - 5432
    ports:
      - ${POSTGRE_PORT}:5432
